# Generated by Django 5.1.5 on 2025-03-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_questionthemes_questionmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmessage',
            old_name='category',
            new_name='theme',
        ),
    ]
