# Generated by Django 5.1.5 on 2025-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_category_questionmessage_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionthemes',
            options={'verbose_name': 'Тема вопроса', 'verbose_name_plural': 'Темы вопросов руководителю'},
        ),
        migrations.AlterField(
            model_name='questionthemes',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Тема вопроса'),
        ),
    ]
