# Generated by Django 5.1.5 on 2025-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_questionthemes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmessage',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
