# Generated by Django 5.1.5 on 2025-04-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_questionmessage_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionmessage',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы руководителю'},
        ),
        migrations.AlterField(
            model_name='questionmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.CreateModel(
            name='PersonalReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.managment', verbose_name='Личный прием ведет')),
            ],
            options={
                'verbose_name': 'Личный прием',
                'verbose_name_plural': 'Личный прием',
            },
        ),
    ]
