# Generated by Django 5.1.5 on 2025-04-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_emergencyservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyservice',
            options={'verbose_name': 'Аварийная служба', 'verbose_name_plural': 'Аварийная служба'},
        ),
        migrations.AlterField(
            model_name='emergencyservice',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
    ]
