# Generated by Django 5.1.5 on 2025-04-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_emergencyservice_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Небытовым потребителям',
                'verbose_name_plural': 'Небытовым потребителям',
            },
        ),
        migrations.CreateModel(
            name='IndividualAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='attachments/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Бытовым потребителям',
                'verbose_name_plural': 'Бытовым потребителям',
            },
        ),
    ]
