# Generated by Django 5.1.5 on 2025-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_entityattachment_individualattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalreception',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
