# Generated by Django 5.1.5 on 2025-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_personalreception_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='managment',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='managment',
            name='birchday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='managment',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='managment',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='managment/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='managment',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендация'),
        ),
        migrations.AlterField(
            model_name='individualattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Файл'),
        ),
    ]
