# Generated by Django 5.1.5 on 2025-04-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_managment_biography_managment_birchday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadingBaseContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_entity', models.TextField(max_length=300, verbose_name='Небытовые потребители whatsapp')),
                ('phones_individual', models.TextField(max_length=300, verbose_name='Бытовым потребителям номера телефонов')),
                ('bots', models.TextField(max_length=50, verbose_name='Бытовым потребителям WhatsAppBot, TelegramBot')),
                ('eMail', models.TextField(max_length=100, verbose_name='Бытовым потребителям eMail')),
                ('phones_private', models.TextField(max_length=300, verbose_name='Частный сектор номера телефонов')),
                ('phones_WhatsApp', models.TextField(max_length=300, verbose_name='Частный сектор whatsapp')),
                ('appart_WhatsApp', models.TextField(max_length=300, verbose_name='Многоэтажные дома whatsapp')),
                ('entity_eMail', models.TextField(max_length=100, verbose_name='Бытовым потребителям eMail')),
            ],
            options={
                'verbose_name': 'Прием показаний',
                'verbose_name_plural': 'Прием показаний',
            },
        ),
    ]
