# Generated by Django 5.1.5 on 2025-04-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_meterreadingbasecontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='appart_WhatsApp',
            field=models.CharField(max_length=300, verbose_name='Многоэтажные дома whatsapp'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='bots',
            field=models.CharField(max_length=50, verbose_name='Бытовым потребителям WhatsAppBot, TelegramBot'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='eMail',
            field=models.CharField(max_length=100, verbose_name='Бытовым потребителям eMail'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='entity_eMail',
            field=models.CharField(max_length=100, verbose_name='Бытовым потребителям eMail'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='phones_WhatsApp',
            field=models.CharField(max_length=300, verbose_name='Частный сектор whatsapp'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='phones_individual',
            field=models.CharField(max_length=300, verbose_name='Бытовым потребителям номера телефонов'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='phones_private',
            field=models.CharField(max_length=300, verbose_name='Частный сектор номера телефонов'),
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='whatsapp_entity',
            field=models.CharField(max_length=300, verbose_name='Небытовые потребители whatsapp'),
        ),
    ]
