# Generated by Django 5.1.5 on 2025-04-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_meterreadingbasecontacts_appart_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetName', models.CharField(max_length=100, verbose_name='Наименование улицы')),
            ],
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='entity_eMail',
            field=models.CharField(max_length=100, verbose_name='Небытовым потребителям eMail'),
        ),
    ]
