# Generated by Django 5.1.5 on 2025-04-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_streets_alter_meterreadingbasecontacts_entity_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streets',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.CreateModel(
            name='MeterReadingBoxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('home', models.CharField(max_length=5, verbose_name='Номер дома')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.streets', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Ящик для приема показаний',
                'verbose_name_plural': 'Ящики для приема показаний',
            },
        ),
    ]
