# Generated by Django 5.1.5 on 2025-04-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_streets_options_meterreadingboxes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreadingbasecontacts',
            old_name='phones_WhatsApp',
            new_name='WhatsApp_private',
        ),
    ]
