# Generated by Django 5.1.5 on 2025-04-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_phones_whatsapp_meterreadingbasecontacts_whatsapp_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Наименование')),
                ('phone', models.TextField(max_length=100, null=True, verbose_name='Телефоны')),
                ('eMail', models.CharField(max_length=100, null=True, verbose_name='eMail')),
            ],
            options={
                'verbose_name': 'Контакты',
            },
        ),
        migrations.AlterField(
            model_name='meterreadingbasecontacts',
            name='appart_WhatsApp',
            field=models.CharField(max_length=300, verbose_name='Многоэтажные дома whatsapp или SMS'),
        ),
    ]
