# Generated by Django 5.1.5 on 2025-04-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_contacts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='contacts',
            name='eMail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='eMail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Телефоны'),
        ),
    ]
