# Generated by Django 5.1.5 on 2025-04-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_contacts_options_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProffesionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('photo', models.FileField(blank=True, null=True, upload_to='profs/', verbose_name='Фото')),
            ],
        ),
    ]
