# Generated by Django 5.1.5 on 2025-04-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_ourproffesionals'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProfessionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('photo', models.FileField(blank=True, null=True, upload_to='profs/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Профессионал',
                'verbose_name_plural': 'Наши профеcсионалы',
            },
        ),
        migrations.DeleteModel(
            name='OurProffesionals',
        ),
    ]
