# Generated by Django 5.1.5 on 2025-04-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_ourprofessionals_delete_ourproffesionals'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('location', models.CharField(max_length=200, verbose_name='')),
                ('workSchedule', models.TextField(max_length=1000, verbose_name='')),
                ('services', models.TextField(max_length=1000, verbose_name='')),
            ],
            options={
                'verbose_name': 'Пункт обслуживания населения',
                'verbose_name_plural': 'Пункты обслуживания населения',
            },
        ),
    ]
