# Generated by Django 5.1.5 on 2025-04-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_publicservicepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('withTax', models.DecimalField(decimal_places=3, max_digits=7, max_length=7, verbose_name='С НДС')),
                ('noTax', models.DecimalField(decimal_places=3, max_digits=7, max_length=7, verbose_name='Без НДС')),
            ],
            options={
                'verbose_name': 'Тарифы',
            },
        ),
        migrations.AlterField(
            model_name='publicservicepoint',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Место расположения'),
        ),
        migrations.AlterField(
            model_name='publicservicepoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Пункт обслуживания населения'),
        ),
        migrations.AlterField(
            model_name='publicservicepoint',
            name='services',
            field=models.TextField(max_length=1000, verbose_name='Комплекс услуг'),
        ),
        migrations.AlterField(
            model_name='publicservicepoint',
            name='workSchedule',
            field=models.TextField(max_length=1000, verbose_name='Режим работы'),
        ),
    ]
