# Generated by Django 5.1.5 on 2025-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rates_alter_publicservicepoint_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rates',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterField(
            model_name='rates',
            name='noTax',
            field=models.DecimalField(decimal_places=2, max_digits=7, max_length=7, verbose_name='Без НДС'),
        ),
    ]
