# Generated by Django 5.1.5 on 2025-04-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_rates_options_alter_rates_notax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='withTax',
            field=models.DecimalField(decimal_places=2, max_digits=7, max_length=7, verbose_name='С НДС'),
        ),
    ]
