# Generated by Django 5.1.5 on 2025-04-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_rates_withtax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='noTax',
            field=models.DecimalField(decimal_places=2, max_digits=7, max_length=10, verbose_name='Без НДС'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='withTax',
            field=models.DecimalField(decimal_places=2, max_digits=7, max_length=10, verbose_name='С НДС'),
        ),
    ]
