# Generated by Django 5.1.5 on 2025-04-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_rates_notax_alter_rates_withtax'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionthemes',
            name='eMail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Электронная почта'),
        ),
    ]
