# Generated by Django 5.1.5 on 2025-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_questionthemes_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Бытовым потребителям',
                'verbose_name_plural': 'Бытовым потребителям',
            },
        ),
    ]
