# Generated by Django 5.1.5 on 2025-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_outages_alter_additionalinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outages',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
