# Generated by Django 5.1.5 on 2025-04-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_outages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='entityattachment',
            name='file',
            field=models.FileField(max_length=500, upload_to='attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='individualattachment',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='managment',
            name='photo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='managment/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ourprofessionals',
            name='photo',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='profs/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='outages',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/', verbose_name='Файл'),
        ),
    ]
