# Generated by Django 5.1.5 on 2025-04-28 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_additionalinformation_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Techspec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='attachments/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Техническое условие',
                'verbose_name_plural': 'Технические условия',
            },
        ),
    ]
