# Generated by Django 5.1.5 on 2025-04-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_techspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('isActive', models.BooleanField(default=False, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Телефоны'),
        ),
    ]
