version: "3.9"

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data # Монтируем каталог, а не конкретный файл
      - static_volume:/app/static # Сохраняем статику
      - media_volume:/app/media # Храним загруженные файлы
    environment:
      - DJANGO_SETTINGS_MODULE=energy.settings # Указываем правильное имя проекта

volumes:
  sqlite_data:
  static_volume:
  media_volume:
